# -*- coding: utf-8 -*-
"""jsonApp.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s6lzADguaootsfTFR3s11X96yROXckIm
"""

!pip install json

import json

import os

class User:
  def __init__(self, username, password, email):
    self.username=username
    self.password=password
    self.email=email

class UserRepository:
  def __init__(self):
    self.users=[]
    self.isLoggedIn=False
    self.currentUser={}
    #load users from .json file
    self.loadUsers()

  def loadUsers(self):
    if os.path.exists('users.json'):
      with open('users.json','r', encoding='utf-8') as file:
        users=json.load(file)
        for user in users:
          user=json.loads(user)
          #print(user['username'])
          newUser=User(username=user['username'],password=user['password'],email=user['email'])
          self.users.append(newUser)
      print(self.users)


  def register(self, user:User):
    print("User created")
    self.users.append(user) #add new user to users list
    self.savetoFile()

  def login(self,username,password):
    if self.isLoggedIn:
      print("already logged in")
    else:
      for user in self.users:
       if user.username==username and user.password==password:
        self.isLoggedIn=True
        self.currentUser=user
        print("user logged in")
        break


  def savetoFile(self):
    list=[]
    for user in self.users:
      list.append(json.dumps(user.__dict__)) #dumps converts object to dictionary, dump saves to file


    with open('users.json','w') as file:
      json.dump(list,file)
      #dump method can not use class data type, convert object to dictionary then use with dump

  def logout(self):
    self.isLoggedIn=False
    self.currentUser={}
    print("user logged out")

  def identity(self):
   if self.isLoggedIn:
      print(f'username:{self.currentUser.username}')
   else:
    print('user did not log in')


repository=UserRepository()

while True:
   print("Menu".center(50,'+'))
   option=input('1-Register\n2-Login\n3-Logout\n4-GetInfo\n')
   if(option=='1'):
    username=input("username: ")
    password=input("password: ")
    email=input("email: ")

    user=User(username=username,password=password,email=email)
    repository.register(user)
    print(repository.users)

   elif(option=='2'):
    if self.isLoggedIn:
      print("already logged in")
    else:
     username=input("username: ")
     password=input("password: ")
     repository.login(username,password)

   elif(option=='3'):
    repository.logout()
   elif(option=='4'):
    repository.identity()
   else:
    break