# -*- coding: utf-8 -*-
"""json2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cC_3ssccITv6tVeKoVVJw0r7rcUcmW5m
"""

!pip install json

import json

person_string='{"name":"Ayse","languages":["python", "Java"]}'

#JSON string to Dict

result=json.loads(person_string)

#print(result)
#print(type(result))

#result1=result["name"]
#print(result1)
#result2=result["languages"]
#print(result2)

try:
    with open("person.json", "r", encoding="utf-8") as f:
        data = json.load(f)
        print(data["name"])
except FileNotFoundError:
    print("Error: File 'person.json' not found.")
except json.JSONDecodeError as e:
    print("Error decoding JSON:", e)

person_dict={
    "name":"ilayda",
    "languages": ["Python","Kotlin"]
}

#dict to JSON str
result=json.dumps(person_dict)
print(result)
#print(result["name"])
print(type(result))

with open("person.json","w") as f:
  json.dump(person_dict,f)

person_string='{"name":"Ayse","languages":["python", "Java"]}'
person_dict={ "name":"ilayda","languages": ["Python","Kotlin"]}

person_dict1=json.loads(person_string)
result=json.dumps(person_dict1, indent=4, sort_keys= True)
print(person_dict1)
print(result)