# -*- coding: utf-8 -*-
"""request_module.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14tgFUB1_l0Bzjzav8KmYffl3dXbyjD8x
"""

import json

print(json.__file__)

import requests  #reach to html with requests, html info like shopping data, website data

result= requests.get("https://jsonplaceholder.typicode.com/todos")
print(result)

result= requests.get("https://jsonplaceholder.typicode.com/todos")
result=json.loads(result.text)
for i in result:
  if i["userId"]==8:
   print(i)
 #print(i["title"])
#print(result[0]["title"])
print(type(result))